language: node_js
node_js:
  - '12'

addons:
  chrome: stable



cache:
  directories:
    - ./node_modules

#install:
  - npm install
#  - npm install -g @angular/cli

script:
  - ng test --watch=false --browsers=ChromeHeadless
#  - ng e2e
